// This file is auto-generated by @hey-api/openapi-ts
import type { Client, Options as Options2, TDataShape } from './client'
import { client } from './client.gen'
import type {
    GetCategoriesData,
    GetCategoriesResponses,
    GetPlacesByIdData,
    GetPlacesByIdResponses,
    GetPlacesData,
    GetPlacesResponses,
    PostRoutesDayData,
    PostRoutesDayResponses
} from './types.gen'

export type Options<
    TData extends TDataShape = TDataShape,
    ThrowOnError extends boolean = boolean
> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>
}

export const getCategories = <ThrowOnError extends boolean = false>(
    options?: Options<GetCategoriesData, ThrowOnError>
) =>
    (options?.client ?? client).get<GetCategoriesResponses, unknown, ThrowOnError>({
        url: '/categories',
        ...options
    })

export const getPlaces = <ThrowOnError extends boolean = false>(
    options?: Options<GetPlacesData, ThrowOnError>
) =>
    (options?.client ?? client).get<GetPlacesResponses, unknown, ThrowOnError>({
        url: '/places',
        ...options
    })

export const getPlacesById = <ThrowOnError extends boolean = false>(
    options: Options<GetPlacesByIdData, ThrowOnError>
) =>
    (options.client ?? client).get<GetPlacesByIdResponses, unknown, ThrowOnError>({
        url: '/places/{id}',
        ...options
    })

export const postRoutesDay = <ThrowOnError extends boolean = false>(
    options?: Options<PostRoutesDayData, ThrowOnError>
) =>
    (options?.client ?? client).post<PostRoutesDayResponses, unknown, ThrowOnError>({
        url: '/routes/day',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    })
