// <auto-generated />
using System;
using ExploreHKMOApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExploreHKMOApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260304162434_InitDatabase")]
    partial class InitDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExploreHKMOApi.Models.PlaceEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoursJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Ranking")
                        .HasColumnType("int");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("ExploreHKMOApi.Models.PlaceEntity", b =>
                {
                    b.OwnsOne("ExploreHKMOApi.Models.Connection", "Connection", b1 =>
                        {
                            b1.Property<int>("PlaceEntityId")
                                .HasColumnType("int");

                            b1.Property<int>("LocationId")
                                .HasColumnType("int");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PlaceEntityId");

                            b1.ToTable("Places");

                            b1.WithOwner()
                                .HasForeignKey("PlaceEntityId");
                        });

                    b.OwnsOne("ExploreHKMOApi.Models.Description", "Description", b1 =>
                        {
                            b1.Property<int>("PlaceEntityId")
                                .HasColumnType("int");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PlaceEntityId");

                            b1.ToTable("Places");

                            b1.WithOwner()
                                .HasForeignKey("PlaceEntityId");
                        });

                    b.OwnsOne("ExploreHKMOApi.Models.Location", "Location", b1 =>
                        {
                            b1.Property<int>("PlaceEntityId")
                                .HasColumnType("int");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.HasKey("PlaceEntityId");

                            b1.ToTable("Places");

                            b1.WithOwner()
                                .HasForeignKey("PlaceEntityId");
                        });

                    b.Navigation("Connection");

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
