import type { Metadata } from 'next'
import { Geist_Mono, Inter } from 'next/font/google'

import { cn } from '@/lib/utils'

import './globals.css'

const latinSans = Inter({
    variable: '--font-latin-sans',
    subsets: ['latin']
})

const latinMono = Geist_Mono({
    variable: '--font-latin-mono',
    subsets: ['latin']
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={cn(
                    latinSans.variable,
                    latinMono.variable,
                    'border-border outline-ring/50', // Default outline colors
                    'text-foreground bg-neutral-50 antialiased **:font-sans!' // Appearance settings
                )}
            >
                {children}
            </body>
        </html>
    )
}
